apiVersion: v1
kind: Template
labels:
  template: jenkins-route
metadata:
  annotations:
    description: jenkins-route
  name: jenkins-route
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: jenkins
    name: jenkins
  spec:
    host: ${HOST}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: jenkins
      weight: 100
    wildcardPolicy: None
parameters:
- description: Host.
  displayName: Host
  name: HOST
  required: true
